create table "public"."test_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "val" boolean default false,
    "user" uuid
);


alter table "public"."test_table" enable row level security;

CREATE UNIQUE INDEX test_table_pkey ON public.test_table USING btree (id);

alter table "public"."test_table" add constraint "test_table_pkey" PRIMARY KEY using index "test_table_pkey";

alter table "public"."test_table" add constraint "test_table_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) not valid;

alter table "public"."test_table" validate constraint "test_table_user_fkey";

create policy "Enable read access for all users"
on "public"."test_table"
as permissive
for select
to public
using (true);


create policy "Enable update for users based on email"
on "public"."test_table"
as permissive
for update
to public
using (true)
with check (true);



